Repository refenv/cijoe, pull requests merged in 2024-12, with the labels that each got.

#112 Add a 'cijoe-docker' image containing everything needed for cijoe and packages
  .github/cijoe-docker/Dockerfile
  .github/workflows/cijoe_docker.yml
Labels: enhancement

#120 feat(ci): add 'meson' to 'cijoe-docker'
  .github/cijoe-docker/Dockerfile
Labels: enhancement

#122 feat(ci): add 'glib2' to 'cijoe-docker'
  .github/cijoe-docker/Dockerfile
Labels: enhancement, documentation

#125 feat(gha): add verification of the cijoe package, fio
  .github/workflows/cijoe_packages.yml
  src/cijoe/fio/configs/example_config_benchmark.toml
  src/cijoe/fio/configs/example_config_default.toml
  src/cijoe/fio/workflows/example_workflow_default.yaml
Labels: bug, enhancement, documentation

#135 refactor(cli): improve example discovery and organization
  .github/workflows/cijoe_packages.yml
  src/cijoe/cli/cli.py
Labels: enhancement

#139 feat(gha): add verification of the cijoe package example; core
  .github/workflows/cijoe_packages.yml
Labels: enhancement

#141 fix(docker): fix AND apt package installation list
  .github/cijoe-docker/Dockerfile
Labels: bug
